### PR TITLE
add LICENSE.txt

### LINKED ISSUE #7: missing LICENSE.txt
The MANIFEST.in file mentions LICENSE.txt, but that doesn't exist in the repository.  That file is also needed for packaging this for various Linux distros.

### PR DESCRIPTION
**Pull request by carlwgeorge**
resolves #7

### CODE REVIEW

**Comment by stedmeister** [comment]
Thanks for doing this.

**Comment by carlwgeorge** [comment]
No problem, happy to help.  Would you mind tagging a new release with this change and pushing it to PyPI?

**Comment by carlwgeorge** [comment]
Ping?

**Comment by stedmeister** [comment]
Just released 0.9.4

**Pull request merged**
